### PR TITLE
Improve sorting by :definition with more than 10 attributes in the list

### PR DESCRIPTION
**Pull request by pilgunboris**
Fixes a bug described here: https://github.com/ElMassimo/oj_serializers/issues/24

### CODE REVIEW

**Review by tblais1224 — APPROVED** [review]
Looks fine to me, approved

**Comment by pilgunboris** [comment]
I guess we might just merge this and then QA it in the context of https://github.com/starburstlabs/crm-web/pull/12156 🤔 
We might try switching between the fork and the original gem to see the difference during testing.

@tblais1224 what do you think?

**Review by mike-leone-wealthbox — APPROVED** [review]
👍

**Comment by mike-leone-wealthbox** [comment]
@pilgunboris merging this and QAing as part of crm-web PR as you described makes sense to me 👍

**Pull request merged**
